// old, was planning to use this but got other ideas.


/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 src/assets/models/nameObject.glb -o src/components/NameObject.tsx -k -K -r public 
*/

import * as THREE from 'three'
import {GradientTexture, useGLTF} from '@react-three/drei'
import { GLTF } from 'three-stdlib'


import {useRef, useState} from "react";

type GLTFResult = GLTF & {
  nodes: {
    Text: THREE.Mesh
  }
  materials: {}
  animations: GLTFAction[]
}

export function NameObject(props: JSX.IntrinsicElements['group']) {
    const ref = useRef()

    const [isHovered, setIsHovered] = useState(false)


    let mousePos = { x: undefined, y: undefined };

    window.addEventListener('mousemove', (event) => {
        mousePos = { x: event.clientX, y: event.clientY };

        // ref.current.position.set( (mousePos.x / 100), (mousePos.y / 100) )
    });


  const {nodes, materials} = useGLTF('/../src/assets/models/nameObject.glb') as GLTFResult
  return (
      <group {...props} dispose={null}>
        <group name="Scene">
            <mesh
                onPointerEnter={(event) => (event.stopPropagation(), setIsHovered(true))}
                onPointerLeave={() => setIsHovered(false)}

                name="nameText"
                geometry={nodes.Text.geometry}
                position={[0, 2.3, 0.2]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            >
                <meshBasicMaterial>
                    <GradientTexture stops={[0, 1]} colors={['aquamarine', 'hotpink']} />
                </meshBasicMaterial>
            </mesh>
        </group>
      </group>
  )
}

useGLTF.preload('/../src/assets/models/nameObject.glb')
