// old, was planning to use this but got other ideas.


/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 src/assets/models/nameObject.glb -o src/components/NameObject.tsx -k -K -r public 
*/

/*
import * as THREE from 'three'
import {GradientTexture, useGLTF} from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Text: THREE.Mesh
  }
  materials: object
}

export function NameObject(props: JSX.IntrinsicElements['group']) {

  const {nodes} = useGLTF('/../src/assets/models/nameObject.glb') as GLTFResult
  return (
      <group {...props} dispose={null}>
        <group name="Scene">
            <mesh
                name="nameText"
                geometry={nodes.Text.geometry}
                position={[0, 2.3, 0.2]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            >
                <meshBasicMaterial>
                    <GradientTexture stops={[0, 1]} colors={['aquamarine', 'hotpink']} />
                </meshBasicMaterial>
            </mesh>
        </group>
      </group>
  )
}

useGLTF.preload('/../src/assets/models/nameObject.glb') */
